import Head from 'next/head'
import styles from '@/styles/Home.module.css'

export default function Home({ title }) {
	return (
		<>
			<Head>
				<title>Travel Events App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<header>
				<nav>
					<a href=''>Home</a>
					<a href='events'>Events</a>
					<a href='about-us'>About us</a>
				</nav>
			</header>
			<main className={`${styles.main}`}>
				<a href='/events/london'>
					<h2>Events in London</h2>
					<p>
						&quot;Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut
						labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris
						nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit
						esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in
						culpa qui officia deserunt mollit anim id est laborum.&quot;
					</p>
				</a>
				<a href='/events/san-francisco'>
					<h2>Events in San Francisco</h2>
					<p>
						&quot;Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut
						labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris
						nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit
						esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in
						culpa qui officia deserunt mollit anim id est laborum.&quot;
					</p>
				</a>
				<a href='/events/barcelona'>
					<h2>Events in Barcelona</h2>
					<p>
						&quot;Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut
						labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris
						nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit
						esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in
						culpa qui officia deserunt mollit anim id est laborum.&quot;
					</p>
				</a>
			</main>
			<footer className={styles.footer}>
				<p>© 2023 Time to Code - A Project Built with Next.js</p>
			</footer>
		</>
	)
}

export function getServerSideProps() {
	return {
		props: {
			title: 'Hello everyone'
		}
	}
}
